name: CI Pipeline - Ubuntu latest

# Definir cuándo se ejecuta el workflow
on:
  push:
    branches: [ main, develop, pipeline, pipeline-dev ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# Definir los jobs del pipeline
jobs:
  # Job 1: Instalación de dependencias
  installation:
    name: "Instalación de Dependencias"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    
    - name: Actualizar sistema
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y \
          curl \
          wget \
          git \
          build-essential \
          python3 \
          python3-pip \
          nodejs \
          npm \
          nginx
    
    - name: Verificar instalaciones
      run: |
        echo "Verificando instalaciones..."
        python3 --version
        node --version
        npm --version
        nginx -v
        echo "✅ Todas las dependencias instaladas correctamente"
    
    - name: Instalar dependencias de Python
      run: |
        pip3 install --upgrade pip
        pip3 install pytest flask requests
    
    - name: Crear archivo de estado de instalación
      run: |
        echo "installation_completed=true" > installation_status.txt
        echo "timestamp=$(date)" >> installation_status.txt
    
    - name: Subir artefactos de instalación
      uses: actions/upload-artifact@v4
      with:
        name: installation-artifacts
        path: installation_status.txt

  # Job 2: Ejecutar tests de prueba
  testing:
    name: "Ejecutar Tests de Prueba"
    runs-on: ubuntu-latest
    needs: installation
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    
    - name: Descargar artefactos de instalación
      uses: actions/download-artifact@v4
      with:
        name: installation-artifacts
    
    - name: Verificar estado de instalación
      run: |
        if [ -f installation_status.txt ]; then
          echo "✅ Archivo de estado encontrado"
          cat installation_status.txt
        else
          echo "❌ Error: No se encontró el archivo de estado"
          exit 1
        fi
    
    - name: Reinstalar dependencias necesarias para tests
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip nodejs npm
        pip3 install --upgrade pip pytest flask requests
    
    - name: Crear directorio de tests
      run: mkdir -p tests

    - name: Crear test de Python
      run: |
        printf 'import sys\nimport subprocess\n\ndef test_python_version():\n    """Test que Python 3 está instalado correctamente"""\n    assert sys.version_info >= (3, 6), "Python 3.6+ requerido"\n    print("✅ Python version test passed")\n\ndef test_pip_installation():\n    """Test que pip está funcionando"""\n    result = subprocess.run(["pip3", "--version"], capture_output=True, text=True)\n    assert result.returncode == 0, "pip3 no está funcionando correctamente"\n    print("✅ Pip installation test passed")\n\ndef test_requests_import():\n    """Test que requests se puede importar"""\n    try:\n        import requests\n        print("✅ Requests import test passed")\n    except ImportError:\n        assert False, "No se puede importar requests"\n' > tests/test_python.py

    - name: Crear test de Node.js
      run: |
        printf "const { exec } = require('child_process');\n\n// Test que Node.js está instalado\nconsole.log('Node.js version:', process.version);\nif (process.version < 'v12.0.0') {\n    console.error('❌ Node.js version muy antigua');\n    process.exit(1);\n}\nconsole.log('✅ Node.js version test passed');\n\n// Test que npm está funcionando\nexec('npm --version', (error, stdout, stderr) => {\n    if (error) {\n        console.error('❌ npm test failed:', error);\n        process.exit(1);\n    }\n    console.log('✅ npm test passed, version:', stdout.trim());\n});\n" > tests/test_node.js

    - name: Crear test del sistema
      run: |
        printf '#!/bin/bash\nset -e\n\necho "🔍 Ejecutando tests del sistema..."\n\n# Test de curl\necho "Testing curl..."\ncurl --version > /dev/null\necho "✅ curl test passed"\n\n# Test de wget\necho "Testing wget..."\nwget --version > /dev/null\necho "✅ wget test passed"\n\n# Test de git\necho "Testing git..."\ngit --version > /dev/null\necho "✅ git test passed"\n\n# Test de nginx\necho "Testing nginx..."\nnginx -v > /dev/null 2>&1\necho "✅ nginx test passed"\n\necho "🎉 Todos los tests del sistema pasaron correctamente"\n' > tests/test_system.sh
        chmod +x tests/test_system.sh
    
    - name: Ejecutar tests de Python
      run: |
        echo "🧪 Ejecutando tests de Python..."
        cd tests
        python3 -m pytest test_python.py -v
    
    - name: Ejecutar tests de Node.js
      run: |
        echo "🧪 Ejecutando tests de Node.js..."
        cd tests
        timeout 10s node test_node.js
    
    - name: Ejecutar tests del sistema
      run: |
        echo "🧪 Ejecutando tests del sistema..."
        cd tests
        ./test_system.sh
    
    - name: Test de conectividad
      run: |
        echo "🌐 Testing conectividad..."
        curl -s https://httpbin.org/ip > /dev/null
        echo "✅ Conectividad test passed"
    
    - name: Crear reporte de tests
      run: |
        echo "# 📊 Reporte de Tests" > test_report.md
        echo "- ✅ Python tests: PASSED" >> test_report.md
        echo "- ✅ Node.js tests: PASSED" >> test_report.md
        echo "- ✅ System tests: PASSED" >> test_report.md
        echo "- ✅ Connectivity tests: PASSED" >> test_report.md
        echo "- 📅 Fecha: $(date)" >> test_report.md
        cat test_report.md
    
    - name: Subir reporte de tests
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test_report.md

  # Job 3: Build y Deploy a Vercel
  deploy:
    name: "Build y Deploy a Vercel"
    runs-on: ubuntu-latest
    needs: [installation, testing]
    if: github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/pipeline' && github.ref != 'refs/heads/pipeline-dev')
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependencias
      run: npm ci
    
    - name: Build para producción
      run: npm run build:vercel
    
    - name: Deploy a Vercel
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
    
    - name: Mensaje de deployment exitoso
      run: |
        echo "🎉 ¡Deployment exitoso a Vercel!"
        echo "🌐 Tu aplicación está disponible en: https://alesky-gym.vercel.app"
        echo "📊 Build completado: $(date)"

  # Job 4: Verificación final y mensaje de éxito
  verification:
    name: "Verificación Final"
    runs-on: ubuntu-latest
    needs: [installation, testing]
    if: always() && (needs.installation.result == 'success' && needs.testing.result == 'success')
    
    steps:
    - name: Descargar artefactos
      uses: actions/download-artifact@v4
      with:
        name: test-report
    
    - name: Verificar que todos los tests pasaron
      run: |
        if [ -f test_report.md ]; then
          echo "📋 Reporte de tests encontrado:"
          cat test_report.md
          
          # Verificar que no hay fallos
          if grep -q "FAILED" test_report.md; then
            echo "❌ Se encontraron tests fallidos"
            exit 1
          else
            echo "✅ Todos los tests pasaron correctamente"
          fi
        else
          echo "❌ No se encontró el reporte de tests"
          exit 1
        fi
    
    - name: Mensaje de éxito final
      run: |
        echo "🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉"
        if [ "${{ github.ref }}" == "refs/heads/pipeline-dev" ]; then
          echo "🧪 ¡PIPELINE DE DESARROLLO COMPLETADO! 🧪"
          echo "🎯 MODO: DESARROLLO - SIN DEPLOY A PRODUCCIÓN"
        else
          echo "🎊 ¡PIPELINE COMPLETADO CON ÉXITO! 🎊"
        fi
        echo "🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉"
        echo ""
        echo "✅ Instalación: COMPLETADA"
        echo "✅ Tests: TODOS PASARON"
        echo "✅ Verificación: EXITOSA"
        echo ""
        if [ "${{ github.ref }}" == "refs/heads/pipeline-dev" ]; then
          echo "🧪 Modo: DESARROLLO - Seguro para experimentar"
          echo "🚫 Deploy: DESHABILITADO (no va a producción)"
        else
          echo "🚀 El sistema está listo para usar en Ubuntu 20.04"
        fi
        echo "📊 Fecha de completación: $(date)"
        echo "🔧 Entorno: Ubuntu 20.04"
        echo "🌟 Estado: PERFECTO"
        echo ""
        echo "🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉"
    
    - name: Crear badge de estado
      run: |
        echo "![Build Status](https://img.shields.io/badge/build-passing-brightgreen)" > build_badge.md
        echo "![Tests](https://img.shields.io/badge/tests-passing-brightgreen)" >> build_badge.md
        echo "![Platform](https://img.shields.io/badge/platform-ubuntu%2020.04-blue)" >> build_badge.md
        
    - name: Mostrar información del entorno
      run: |
        echo "🔍 Información del entorno:"
        echo "- OS: $(lsb_release -d | cut -f2)"
        echo "- Kernel: $(uname -r)"
        echo "- Architecture: $(uname -m)"
        echo "- CPU: $(nproc) cores"
        echo "- Memory: $(free -h | grep '^Mem:' | awk '{print $2}')"
        echo "- Disk: $(df -h / | tail -1 | awk '{print $4}') available"
